[versions]
gradleVersion = "8.6.1"
kotlinVersion = "2.2.0"
desugar = "2.1.3"

[libraries]
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "gradleVersion" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinVersion" }
kotlin-serialization-plugin = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlinVersion" }
kotlin-compose-compiler-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlinVersion" }
tools-desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }